### ISSUE TITLE
YAML parser does not accept valid yaml

### ISSUE THREAD

**Issue by serkonda7** [github-linguist/linguist#6438]
The following yaml fails with error
```
- Grammar conversion failed. File `syntaxes/vba.yaml-tmlanguage` failed to parse: yaml: line 53: found unknown escape character
```

```yaml
# This file is part of vscode-vba.
# Copyright (c) 2021-2022 Lukas Neubert
# Use of this source file is governed by the MIT license.

name: Visual Basic for Applications
scopeName: source.vba
fileTypes:
  - .bas
  - .cls
  - .frm

patterns:
  - include: "#comments"
  - include: "#keywords"
  - include: "#numbers"
  - include: "#storage"
  - include: "#strings"
  - include: "#types"
  - include: "#functions"
  - name: constant.other.vba
    match:  _(?=\s*\n)

repository:
  comments:
    name: comment.line.quote
    begin: "'"
    end: $

  keywords:
    patterns:
      - name: keyword.other.option.vba
        match: (?i)\bOption (Base [01]|Compare (Binary|Text)|Explicit|Private Module)\b
      - name: keyword.conditional.vba
        match: (?i:\b(Do(( While)|( Until))?|While|Case( Else)?|Else(If)?|For( Each)?|(I)?If|In|New|(Select )?Case|Then|To|Step|With)\b)
      - name: keyword.conditional.end.vba
        match: (?i:\b(End( )?If|End (Select|With)|Next|Wend|Loop(( While)|( Until))?|Exit (For|Do|While))\b)
      - name: keyword.control.vba
        match: (?i:(\b(Exit (Function|Property|Sub)|As|And|By(Ref|Val)|Goto|Is|Like|Mod|Not|On Error|Optional|Or|Resume Next|Stop|Xor|Eqv|Imp|TypeOf|AddressOf)\b)|(\b(End)\b(?=\n)))
      - name: keyword.other.vba
        match: (?i:\b(Attribute|Call|End (Function|Property|Sub|Type|Enum)|(Static )?(Const|Function|Property|Sub|Type|Enum)|Declare|PtrSafe|WithEvents|Event|RaiseEvent)\b)
      - name: keyword.other.visibility.vba
        match: (?i:\b(Private|Public|Friend)\b)
      - name: constant.language.vba
        match: (?i)\b(Empty|False|Nothing|Null|True)\b

  functions:
    name: entity.name.function.vba
    match: (?i:\b(?<=(Call|Function|Sub)\s)[a-zA-Z][a-zA-Z0-9_]*\b)(?=\(\)?)

  numbers:
    patterns:
      - name: constant.numeric.date
        match: "(?i)#((Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)|[0-9]{1,2})(-|\/)[0-9]{1,2}((-|\/)[0-9]{1,4})?#"
      - name: constant.numeric.decimal
        match: (?<!\w)-?\d+(\.\d+)?
      - name: constant.numeric.octal
        match: (?i)-?&O[0-7]+
      - name: constant.numeric.hexadecimal
        match: (?i)-?&H[0-9A-F]+

  storage:
    patterns:
      - name: storage.modifier.vba
        match: (?i)\b(Class|Const|Dim|(G|L|S)et|ReDim( Preserve)?|Erase)\b

  strings:
    name: string.quoted.double
    begin: '"'
    end: '"'

  types:
    patterns:
      - name: support.type.builtin.vba
        match: (?i)\b(Any|Byte|Boolean|Currency|Collection|Date|Double|Integer|Long(Long|Ptr)?|Object|Single|String|Variant)\b
      - match: (?i)(?<=\s+As\s+)([a-zA-Z]+)
        captures:
          1:
            name: support.type

```
